amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2 # 회전 시 회전 오차
    alpha2: 0.2 # 직진 시 회전 오차
    alpha3: 0.2 # 직진 시 직진 오차
    alpha4: 0.2 # 회전 시 직진 오차
    alpha5: 0.2 # omni용 드리프트

    base_frame_id: "base_footprint"
    global_frame_id: "map"

    beam_skip_distance: 0.5 # 라이다 beam 차이가 이 거리 이상이면 skip 후보
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false

    lambda_short: 0.1 # 예상보다 짧은 거리 측정 확률 모델
    laser_likelihood_max_dist: 2.0 # likelihood field 최대 거리
    laser_max_range: 9.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 90 # 라이다 데이터
    max_particles: 3000 # 초기 검증용 위치추정 particle 수
    min_particles: 800
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    set_initial_pose: false
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.10
    update_min_d: 0.10
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: "/scan"
bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: "map"
    robot_base_frame: "base_footprint"
    odom_topic: "/odometry/filtered"
    bt_loop_duration: 10
    default_server_timeout: 2000
    default_cancel_timeout: 2000
    wait_for_service_timeout: 3000 #ms
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    odom_topic: "/odometry/filtered"
    min_x_velocity_threshold: 0.001 # 이 값 이하 속도는 0 처리
    min_y_velocity_threshold: 0.5   # 홀로노믹용
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.5 # 이 값 이상 실패율이면 recovery
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3 # 이 거리 이상 이동 못하면 stuck 판단
      movement_time_allowance: 30.0 # 몇 초 동안 움직임 없으면 recovery
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25 # 목표 위치 허용 오차
      yaw_goal_tolerance: 0.3  # 목표 각도 허용 오차
      stateful: true
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.18 # 목표 직진 속도
      lookahead_dist: 0.9    # 추종 경로 지정
      min_lookahead_dist: 0.4  # 추종점 최소 거리
      max_lookahead_dist: 1.0
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 0.20  # 제자리 회전 속도
      transform_tolerance: 0.3
      use_velocity_scaled_lookahead_dist: false # 속도에 따라 lookahead를 자동 조절
      min_approach_linear_velocity: 0.05  # goal 접근 시 최소 선속도
      approach_velocity_scaling_dist: 0.6 # goal 근처 감속을 시작하는 거리
      use_collision_detection: true # 경로 충돌 예측
      max_allowed_time_to_collision_up_to_carrot: 1.6 # 현재 속도로 전방 충돌까지 허용 시간
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 0.9  # 이 회전 반경보다 작으면 속도 제한 적용
      regulated_linear_scaling_min_speed: 0.1
      cost_scaling_dist: 0.4  # 장애물 가까워질 때 감속 시작 거리
      cost_scaling_gain: 1.0  # cost 기반 감속 강도
      inflation_cost_scaling_factor: 3.0  # 장애물 근처 cost 증가 정도
      use_rotate_to_heading: false # 경로 시작 방향이나 goal 방향에 맞추기 위해 제자리 회전 사용
      rotate_to_heading_min_angle: 0.785  # 
      max_angular_accel: 0.4  # 최대 각가속도
      max_robot_pose_search_dist: 10.0  # 경로 위에서 로봇과 가장 가까운 pose를 찾는 최대 거리
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 5.0
      publish_frequency: 2.0
      transform_tolerance: 0.3
      global_frame: "odom"
      robot_base_frame: "base_footprint"
      rolling_window: true  
      width: 3
      height: 3 # 로컬 맵 크기
      resolution: 0.05  # 해상도
      footprint: "[[0.255, 0.355], [0.255, -0.355], [-0.575, -0.355], [-0.575, 0.355]]" # 로봇 실제 크기
      plugins: ["obstacle_layer", "inflation_layer"]  # costmap에 사용할 layer 목록
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true 
        observation_sources: "scan"
        scan:
          topic: "/scan"
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 2.0   # clear 영역 최대 거리
          raytrace_min_range: 0.0
          obstacle_max_range: 2.3   # 장애물 등록 최대 거리
          obstacle_min_range: 0.1
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55  # 장애물 주변 안전 반경
      always_send_full_costmap: true

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: "map"
      robot_base_frame: "base_footprint"
      footprint: "[[0.255, 0.355], [0.255, -0.355], [-0.575, -0.355], [-0.575, 0.355]]"
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: "scan"
        scan:
          topic: "/scan"
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 4.0
          raytrace_min_range: 0.0
          obstacle_max_range: 3.0
          obstacle_min_range: 0.1
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.0
        inflation_radius: 0.7  # 장애물 주변 안전 반경
      always_send_full_costmap: true

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: false
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: true

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 20.0 # 경로 재계산 주기
    planner_plugins: ["GridBased"]  
    GridBased:
      plugin: "nav2_smac_planner::SmacPlanner2D"
      tolerance: 0.25 # 목표 근처 몇 m까지 경로 허용할지
      downsample_costmap: false
      downsampling_factor: 1
      allow_unknown: false  # 미탐색 영역 통과 허용
      max_iterations: 1000000 # 경로 탐색 반복 최대 횟수
      max_on_approach_iterations: 1000  # 목표 근처 접근 단계에서 추가 탐색 반복 제한
      max_planning_time: 2.0  # 경로 탐색 시간
      cost_travel_multiplier: 5.0 # 장애물 근처 cost 가중치
      use_final_approach_orientation: false
      smooth_path: true
    costmap_update_timeout: 1.7
    # GridBased:
    #   plugin: "nav2_navfn_planner::NavfnPlanner"
    #   tolerance: 0.5
    #   use_astar: false
    #   allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true

behavior_server:
  ros__parameters:
    use_sim_time: false
    costmap_topic: "local_costmap/costmap_raw"
    footprint_topic: "local_costmap/published_footprint"
    cycle_frequency: 10.0
    # 사용할 recovery/behavior 목록 (회전, 후진, 직진, 대기)
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait", "assisted_teleop"]  
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    global_frame: "odom"
    robot_base_frame: "base_footprint"
    transform_tolerance: 0.3
    simulate_ahead_time: 2.0  # behavior 실행 전 전방 시뮬레이션 시간
    max_rotational_vel: 0.20  # spin 동작 최대 회전 속도
    min_rotational_vel: 0.1   # spin 동작 최소 회전 속도
    rotational_acc_lim: 0.5

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint" # waypoint 도착 후 실행할 task plugin
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true # waypoint task executor 활성화
      waypoint_pause_duration: 0  # waypoint 도착 후 대기 시간(ms)

velocity_smoother:
  ros__parameters:
    use_sim_time: false
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP" # smoothing 기준 - OPEN_LOOP: 단순/안정. CLOSED_LOOP: 실제 속도 반영
    max_velocity: [0.18, 0.0, 0.20] # 최대 속도 x y theta
    min_velocity: [-0.1, 0.0, -0.20]
    max_accel: [0.25, 0.0, 0.4]  # 최대 가속도
    max_decel: [-0.25, 0.0, -0.4]
    odom_topic: "/odometry/filtered"
    odom_duration: 0.1  # CLOSED_LOOP에서 odom 속도 추정에 사용할 시간
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - "controller_server"
      - "smoother_server"
      - "planner_server"
      - "behavior_server"
      - "bt_navigator"
      - "waypoint_follower"
      - "velocity_smoother"

lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - "map_server"
      - "amcl"
