scan_filter_node:
  ros__parameters:
    input_scan_topic: /scan_raw
    output_scan_topic: /scan
    enabled: true
    center_angle_rad: 0.0
    remove_angle_width_rad: 0.06
    use_nan: true
    replacement_range: 0.0
    debug_log: false
