encoder_odom_node:
  ros__parameters:
    encoder_ticks_topic: "/encoder_ticks"
    odom_topic: "/odom_raw"
    odom_frame: "odom"
    base_frame: "base_footprint"
    wheel_radius: 0.0625
    wheel_separation: 0.35
    ticks_per_revolution: 75.0
    publish_tf: false
    left_tick_sign: 1.0
    right_tick_sign: 1.0
    enable_tick_outlier_reject: false
    max_abs_delta_ticks: 15.0
    max_abs_tick_difference: 8.0
    max_linear_velocity: 1.0
    max_angular_velocity: 4.0
