scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: front_180_crop
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -1.5708
        upper_angle: 1.5708
