tof_node:
  ros__parameters:
    gpio_chip: "/dev/gpiochip4"
    i2c_bus: 1
    publish_rate_hz: 20.0
    publish_rate: 20.0
    timeout_sec: 0.5
    read_timeout_ms: 20
    min_range: 0.03
    max_range: 1.2
    field_of_view: 0.436
    sensors:
      - front_right
      - front_left
      - rear_right
      - rear_left
      - rear_center
    front_right:
      type: "VL53L0X"
      xshut_gpio: 17
      i2c_address: 0x30
      frame_id: "tof_front_right_link"
      topic: "/tof/front_right"
      max_range_m: 1.2
      read_timeout_ms: 20
    front_left:
      type: "VL53L0X"
      xshut_gpio: 27
      i2c_address: 0x31
      frame_id: "tof_front_left_link"
      topic: "/tof/front_left"
      max_range_m: 1.2
      read_timeout_ms: 20
    rear_right:
      type: "VL53L0X"
      xshut_gpio: 22
      i2c_address: 0x32
      frame_id: "tof_rear_right_link"
      topic: "/tof/rear_right"
      max_range_m: 1.2
      read_timeout_ms: 20
    rear_left:
      type: "VL53L0X"
      xshut_gpio: 23
      i2c_address: 0x33
      frame_id: "tof_rear_left_link"
      topic: "/tof/rear_left"
      max_range_m: 1.2
      read_timeout_ms: 20
    rear_center:
      type: "VL53L1X"
      xshut_gpio: 25
      i2c_address: 0x34
      frame_id: "tof_rear_center_link"
      topic: "/tof/rear_center"
      max_range_m: 2.0
      read_timeout_ms: 20
